"""Fixed workflow services. Evidence and values are carried through, never regenerated by AI."""

import json
import logging
from typing import TypedDict
from uuid import uuid4

from agent import feedback
from agent.ai import AIService, RankingResult
from agent.domain import CompanionExperience, CustomerContext, IntentContext, Recommendation, TraceStep, ValueSummary
from agent.intent_engine import IntentEngine
from agent.matching import MatchingEngine, MatchResult
from agent.repositories import Abstain, Repository
from agent.value_calculation import ValueCalculationService
from config.settings import Settings

logger = logging.getLogger("intent_companion")


class WorkflowState(TypedDict, total=False):
    customer_id: str
    intent_id: str
    customer: CustomerContext
    intent: IntentContext
    matches: MatchResult
    recommendations: list[Recommendation]
    values: list[ValueSummary]
    ranking: RankingResult
    experience: CompanionExperience


class CompanionService:
    def __init__(self, repository: Repository, settings: Settings, ai: AIService):
        self.repository, self.settings, self.ai = repository, settings, ai
        self.intent_engine = IntentEngine(repository, settings)
        self.matching = MatchingEngine(repository, settings)
        self.value_service = ValueCalculationService()
        self.graph = None

    async def guard(self, state: WorkflowState) -> dict:
        customer = self.repository.customer(state["customer_id"])
        stored = self.repository.intent(state["intent_id"])
        intent = self.intent_engine.refresh(customer, stored)
        if feedback.status(self.repository, feedback.consumer_key(intent)) == "dismissed":
            raise Abstain("This trip intent was dismissed. Restore it explicitly to see recommendations.")
        if intent.confidence <= 0:
            raise Abstain("There is insufficient signal evidence to personalize this trip.")
        return {"customer": customer, "intent": intent}

    async def retrieve(self, state: WorkflowState) -> dict:
        return {"matches": self.matching.match(state["customer"], state["intent"])}

    async def calculate(self, state: WorkflowState) -> dict:
        matches = state["matches"]
        recommendations, values = self.value_service.apply(matches.recommendations, matches.items)
        if not any(r.recommendation_type != "card" for r in recommendations):
            raise Abstain("No verified recommendation is available for this scenario.")
        return {"recommendations": recommendations, "values": values}

    async def rank(self, state: WorkflowState) -> dict:
        return {"ranking": await self.ai.rank_recommendations(state["recommendations"], state["intent"].preferences)}

    async def compose(self, state: WorkflowState) -> dict:
        customer, intent, ranking = state["customer"], state["intent"], state["ranking"]
        # A preference/consent update while an external model is pending invalidates the result.
        if self.repository.customer(customer.customer_id) != customer:
            raise Abstain("Preferences or consent changed during generation. Regenerate the experience.")
        self.intent_engine.refresh(customer, intent)
        if feedback.status(self.repository, feedback.consumer_key(intent)) == "dismissed":
            raise Abstain("This trip intent was dismissed during generation.")
        grouped = {
            kind: [r for r in ranking.recommendations if r.recommendation_type == kind]
            for kind in ("card", "benefit", "offer", "reward", "merchant")
        }
        top_card = grouped["card"][0] if grouped["card"] else None
        if not top_card:
            raise Abstain("No verified card product is available for this scenario.")
        preference_text = ", ".join(intent.preferences) or "your travel context"
        headline = "Rome, made for your kind of journey."
        summary = (
            f"Explore {top_card.title} for {preference_text}. Contextually relevant based on your trip and mock product facts."
            if customer.lifecycle_stage == "prospect"
            else f"Of your held demo cards, {top_card.title} leads for {preference_text}."
        )
        value_order = {r.product_ids[0]: i for i, r in enumerate(grouped["card"])}
        experience = CompanionExperience(
            experience_id=f"experience-{uuid4().hex}",
            customer_id=customer.customer_id,
            lifecycle_stage=customer.lifecycle_stage,
            intent=intent,
            headline=headline,
            summary=summary,
            recommended_cards=grouped["card"],
            benefits=grouped["benefit"],
            offers=grouped["offer"],
            rewards=grouped["reward"],
            merchants=grouped["merchant"],
            value_summary=sorted(state["values"], key=lambda v: value_order.get(v.product_id, 100)),
            explanations=[r.explanation for r in ranking.recommendations],
            preferences_used=intent.preferences,
            status="ready",
            provider_mode=ranking.mode,
            fallback_reason=ranking.fallback_reason,
            generated_at=self.settings.now(),
            trace=[
                TraceStep(
                    stage="Detect",
                    description="Permissioned signals normalized; repeated signal types count once.",
                    count=len(intent.signal_ids),
                ),
                TraceStep(
                    stage="Understand",
                    description=f"{intent.intent_stage.title()} Rome travel intent; confidence is a documented heuristic.",
                    count=len(intent.preferences),
                ),
                TraceStep(
                    stage="Activate",
                    description=f"{state['matches'].retrieved_count} candidates retrieved; rules and value checks applied before ranking.",
                    count=len(ranking.recommendations),
                ),
            ],
        )
        return {"experience": experience}

    async def run(self, customer_id: str, intent_id: str) -> CompanionExperience:
        # Ownership/unknown-ID errors remain 404 even if the profile cannot personalize.
        customer = self.repository.customer(customer_id)
        stored = self.repository.intent(intent_id)
        if stored.customer_id != customer_id:
            from agent.repositories import NotFound

            raise NotFound("Unknown intent for this customer")
        try:
            result = await self.graph.ainvoke({"customer_id": customer_id, "intent_id": intent_id})
            experience = result["experience"]
        except Abstain as exc:
            experience = CompanionExperience(
                experience_id=f"experience-{uuid4().hex}",
                customer_id=customer_id,
                lifecycle_stage=customer.lifecycle_stage,
                status="abstained",
                headline="No verified recommendation is available for this scenario.",
                summary="We need current, permissioned evidence before personalizing this experience.",
                abstention_reasons=[str(exc)],
                generated_at=self.settings.now(),
            )
        self.repository.audit(experience)
        logger.info(
            json.dumps(
                {
                    "event": "experience_generated",
                    "experience_id": experience.experience_id,
                    "intent_id": intent_id,
                    "status": experience.status,
                    "provider": experience.provider_mode,
                    "fallback": bool(experience.fallback_reason),
                    "recommendations": sum(
                        len(getattr(experience, k))
                        for k in ("recommended_cards", "benefits", "offers", "rewards", "merchants")
                    ),
                }
            )
        )
        return experience
